package Objetos;
// Generated 03/06/2016 10:35:37 by Hibernate Tools 4.3.1



/**
 * Assiduidade generated by hbm2java
 */
public class Assiduidade  implements java.io.Serializable {


     private AssiduidadeId id;
     private Matricula matricula;
     private boolean presenca;

    public Assiduidade() {
    }

    public Assiduidade(AssiduidadeId id, Matricula matricula, boolean presenca) {
       this.id = id;
       this.matricula = matricula;
       this.presenca = presenca;
    }
   
    public AssiduidadeId getId() {
        return this.id;
    }
    
    public void setId(AssiduidadeId id) {
        this.id = id;
    }
    public Matricula getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(Matricula matricula) {
        this.matricula = matricula;
    }
    public boolean isPresenca() {
        return this.presenca;
    }
    
    public void setPresenca(boolean presenca) {
        this.presenca = presenca;
    }




}


