package Objetos;
// Generated 03/06/2016 10:35:37 by Hibernate Tools 4.3.1


import Util.FormatoDataHora;
import Util.HibernateUtil;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Disciplina generated by hbm2java
 */
public class Disciplina  implements java.io.Serializable {
     private String codigo;
     private Seminario seminario;
     private String nome;
     private Set turmas = new HashSet(0);

    public Disciplina() {
    }

	
    public Disciplina(String codigo, Seminario seminario, String nome) {
        this.codigo = codigo;
        this.seminario = seminario;
        this.nome = nome;
    }
    public Disciplina(String codigo, Seminario seminario, String nome, Set turmas) {
       this.codigo = codigo;
       this.seminario = seminario;
       this.nome = nome;
       this.turmas = turmas;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Seminario getSeminario() {
        return this.seminario;
    }
    
    public void setSeminario(Seminario seminario) {
        this.seminario = seminario;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getTurmas() {
        return this.turmas;
    }
    
    public void setTurmas(Set turmas) {
        this.turmas = turmas;
    }
    
    //////////////////////////////////////////////
    
    public static Disciplina selectDisciplinaPk(String codigo){
        return (Disciplina)HibernateUtil.getTuplasDaTabela("Disciplina", "codigo='"+codigo+"'").get(0);
    }
    
    public static List<Disciplina> listarTodos(){
        return HibernateUtil.getTuplasDaTabela("Disciplina");
    }
    
    public List<Turma> getTodasTurmas(){
        List<Turma> turmasDaDisciplina = HibernateUtil.getTuplasDaTabela("Turma", "codigo='"+this.codigo+"'");
        turmasDaDisciplina = Turma.completarInfoDisciplina(turmasDaDisciplina); //Falta um select mais eficiente
        return turmasDaDisciplina;
    }
    
    public List<Turma> getTurmasAtivas(Date dataAtual){
        List<Turma> turmasAtivas = HibernateUtil.getTuplasDaTabela("Turma", "codigo='"+this.codigo+"' and '"+FormatoDataHora.sqlData(dataAtual)+"' between data_inicio and data_fim");
        turmasAtivas = Turma.completarInfoDisciplina(turmasAtivas);
        return turmasAtivas;
    }

    public void cadastrarTurma(Membro professor, PeriodoLetivo periodo, Date dataInicio, Date dataFim){
        Turma turma = new Turma( new TurmaId(codigo,dataInicio), this, professor, periodo, dataFim);
        HibernateUtil.persistirObjeto(turma);
    }

    public void cadastrarTurma(Turma turma){
        HibernateUtil.persistirObjeto(turma);
    }


}


