package Objetos;
// Generated 03/06/2016 10:35:37 by Hibernate Tools 4.3.1


import Util.FormatoDataHora;
import Util.HibernateUtil;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.criterion.Restrictions;

/**
 * Evento generated by hbm2java
 */
public class Evento  implements java.io.Serializable {


     private EventoId id;
     private String publicoAlvo;
     private String tipo;
     private Set ministracoes = new HashSet(0);
     private Set visitantes = new HashSet(0);
     private Set noticias = new HashSet(0);

    public Evento() {
    }

	
    public Evento(EventoId id, String tipo) {
        this.id = id;
        this.tipo = tipo;
    }
    public Evento(EventoId id, String publicoAlvo, String tipo, Set ministracaos, Set visitantes, Set noticias) {
       this.id = id;
       this.publicoAlvo = publicoAlvo;
       this.tipo = tipo;
       this.ministracoes = ministracaos;
       this.visitantes = visitantes;
       this.noticias = noticias;
    }
   
    public EventoId getId() {
        return this.id;
    }
    
    public void setId(EventoId id) {
        this.id = id;
    }
    public String getPublicoAlvo() {
        return this.publicoAlvo;
    }
    
    public void setPublicoAlvo(String publicoAlvo) {
        this.publicoAlvo = publicoAlvo;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getMinistracoes() {
        return this.ministracoes;
    }
    
    public void setMinistracoes(Set ministracaos) {
        this.ministracoes = ministracaos;
    }
    public Set getVisitantes() {
        return this.visitantes;
    }
    
    public void setVisitantes(Set visitantes) {
        this.visitantes = visitantes;
    }
    public Set getNoticias() {
        return this.noticias;
    }
    
    public void setNoticias(Set noticias) {
        this.noticias = noticias;
    }
    
    ////////////////////////////////////////////////////////////
    
    public static Evento preencherDadosEvento(Object[] object, int index){
        Evento evento = new Evento();
        evento.setId(new EventoId((String)object[index],(Date)object[index+1]));
        evento.setPublicoAlvo((String)object[index+2]);
        evento.setTipo((String)object[index+3]);
        return evento;
    }
    
    public static List<Evento> preencherDadosEvento(List<Object[]> objects, int index){
        List<Evento> eventos = new ArrayList();
        for(Object[] obj: objects){
            eventos.add(preencherDadosEvento(obj,index));
        }
        return eventos;
    }
    
    public static Evento selectEventoPk(EventoId id){
        List<Object[]> objects = HibernateUtil.getTuplasDaTabela("Evento", "tema="+id.getTema() + " and dia_hora='"+FormatoDataHora.sqlDataHora(id.getDiaHora())+"'","");
        return preencherDadosEvento(objects.get(0),0);
    }
    
    public static Evento selectEventoPk(String tema, Date dia_hora){
        //CONFERRIR STRING DE DIA_HORA!!!
        List<Object[]> objects = HibernateUtil.getTuplasDaTabela("Evento", "tema='"+tema+"'" + " and dia_hora='"+dia_hora+"'","");
        return preencherDadosEvento(objects.get(0),0);
    }
       
    public static List<Evento> listarTodos(){
        List<Object[]> objects = HibernateUtil.getTuplasDaTabela("Evento");
        return preencherDadosEvento(objects,0);
    }
    
    public static List<Evento> listarTodos(Ordem ordem){
        List<Object[]> objects = HibernateUtil.getTuplasDaTabela("Evento","","dia_hora "+ ordem.getSqlOrder());
        return preencherDadosEvento(objects, 0);
    }
    
    public static List<Evento> listarTodos(Ordem ordem, int numMaxResultados){
        List<Object[]> objects = HibernateUtil.getTuplasDaTabela("Evento","","dia_hora "+ ordem.getSqlOrder(),numMaxResultados);
        return preencherDadosEvento(objects, 0);
    }
    
    public static List<Evento> selectEventoPorTema(String tema){
        return HibernateUtil.getTuplasDaTabela("Evento","tema="+tema,"");
    }
    
    public static List<Evento> selectEventoPorTema(String tema, Ordem ordem){
        return HibernateUtil.getTuplasDaTabela("Evento","tema='"+tema+"'"," order by dia_hora"+ ordem.getSqlOrder());
    }
    
    public void adicionarVisitante(Pessoa pessoa){
        Visitante visitante = new Visitante(pessoa);
        List<String> parametros = new ArrayList<>();
        parametros.add(""+visitante.getId());
        //Parâmetros do banco que se referem à Strings ou chars, precisam de aspas simples
        parametros.add("'"+this.id.getDiaHora()+"'");
        parametros.add("'"+this.id.getTema()+"'");
        HibernateUtil.insertInto("Visita_Evento", parametros);
    }

    //Criado por Rafael em 01/06
    //Verificar exception
    public void adicionarVisitante(Visitante visitante){
        List<String> parametros = new ArrayList<>();
        parametros.add(""+visitante.getId());
        //Parâmetros do banco que se referem à Strings ou chars, precisam de aspas simples
        parametros.add("'"+this.id.getDiaHora()+"'");
        parametros.add("'"+this.id.getTema()+"'");
        HibernateUtil.insertInto("Visita_Evento", parametros);
    }

    public void cadastrarMinistracao(Pessoa pessoa, Mensagem mensagem){
        Ministracao ministracao = new Ministracao(new MinistracaoId(this.getId().getTema(),this.getId().getDiaHora(),mensagem.getTitulo()),this,mensagem,pessoa);
        HibernateUtil.persistirObjeto(ministracao);
    }

    public void cadastrarMinistracao(Ministracao ministracao){
        HibernateUtil.persistirObjeto(ministracao);
    }


}


