package Objetos;
// Generated 03/06/2016 10:35:37 by Hibernate Tools 4.3.1


import Util.HibernateUtil;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Matricula generated by hbm2java
 */
public class Matricula  implements java.io.Serializable {


     private MatriculaId id;
     private Membro aluno;
     private Turma turma;
     private Float notaFinal;
     private Set assiduidades = new HashSet(0);

    public Matricula() {
    }

	
    public Matricula(MatriculaId id, Membro membro, Turma turma) {
        this.id = id;
        this.aluno = membro;
        this.turma = turma;
    }
    public Matricula(MatriculaId id, Membro membro, Turma turma, Float notaFinal, Set assiduidades) {
       this.id = id;
       this.aluno = membro;
       this.turma = turma;
       this.notaFinal = notaFinal;
       this.assiduidades = assiduidades;
    }
   
    public MatriculaId getId() {
        return this.id;
    }
    
    public void setId(MatriculaId id) {
        this.id = id;
    }
    public Membro getAluno() {
        return this.aluno;
    }
    
    public void setAluno(Membro aluno) {
        this.aluno = aluno;
    }
    public Turma getTurma() {
        return this.turma;
    }
    
    public void setTurma(Turma turma) {
        this.turma = turma;
    }
    public Float getNotaFinal() {
        return this.notaFinal;
    }
    
    public void setNotaFinal(Float notaFinal) {
        this.notaFinal = notaFinal;
    }
    public Set getAssiduidades() {
        return this.assiduidades;
    }
    
    public void setAssiduidades(Set assiduidades) {
        this.assiduidades = assiduidades;
    }

    public void cadastrarAssiduidade(Date data, boolean presenca){
        Assiduidade assiduidade = new Assiduidade(new AssiduidadeId(data,aluno.getId(),turma.getDisciplina().getCodigo(),turma.getId().getDataInicio()),this,presenca);
        HibernateUtil.persistirObjeto(assiduidade);
    }

    public void cadastrarAssiduidade(Assiduidade assiduidade){
        HibernateUtil.persistirObjeto(assiduidade);
    }


}


