package Objetos;
// Generated 03/06/2016 10:35:37 by Hibernate Tools 4.3.1

import Util.HibernateUtil;




/**
 * Ministracao generated by hbm2java
 */
public class Ministracao  implements java.io.Serializable {


     private MinistracaoId id;
     private Evento evento;
     private Mensagem mensagem;
     private Pessoa pessoa;

    public Ministracao() {
        this.id = new MinistracaoId();
    }

    public Ministracao(Evento evento, Mensagem mensagem, Pessoa pessoa) {
       this.id = new MinistracaoId();
       setEvento(evento);
       setMensagem(mensagem);
       this.pessoa = pessoa;
    }
   
    public MinistracaoId getId() {
        return this.id;
    }
    
    public void setId(MinistracaoId id) {
        this.id = id;
    }
    public Evento getEvento() {
        return this.evento;
    }
    
    public final void setEvento(Evento evento) {
        this.evento = evento;
        this.id.setDiaHoraEvt(evento.getId().getDiaHora());
        this.id.setTemaEvt(evento.getId().getTema());
    }
    public Mensagem getMensagem() {
        return this.mensagem;
    }
    
    public final void setMensagem(Mensagem mensagem) {
        this.mensagem = mensagem;
        this.id.setTituloMsg(mensagem.getTitulo());
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    //Ver necessidade de retornar objeto cadastrado no banco
    public static Ministracao cadastrarOuAtualizarMinistracao(Evento evento,Pessoa pessoa, Mensagem mensagem){
        Ministracao ministracao = new Ministracao(evento,mensagem,pessoa);
        HibernateUtil.persistirObjeto(ministracao);
        return ministracao;
    }

    public static void cadastrarOuAtualizarMinistracao(Ministracao ministracao){
        HibernateUtil.persistirObjeto(ministracao);
    }
    
    public static void deletarMinistracao(Ministracao ministracao){
        HibernateUtil.deletarObjeto(ministracao);
    }
    

}


