package Objetos;
// Generated 03/06/2016 10:35:37 by Hibernate Tools 4.3.1

import Util.HibernateUtil;
import Util.Returner;
import java.util.List;




/**
 * Noticia generated by hbm2java
 */
public class Noticia  implements java.io.Serializable {

     private Integer id;
     private String manchete;
     private Evento evento;
     private Membro membro;
     private String texto;

    public Noticia() {
    }
	
    public Noticia(Integer id, String manchete, Membro membro, String texto) {
        this.id = id;
        this.manchete = manchete;
        this.membro = membro;
        this.texto = texto;
    }
    
    public Noticia(int id, String manchete, Evento evento, String texto) {
        this.id = id;
        this.manchete = manchete;
        this.evento = evento;
        this.texto = texto;
    }
    
    public Noticia(int id, String manchete, String texto, Evento evento, Membro membro) {
       this.id = id;
       this.manchete = manchete;
       this.evento = evento;
       this.membro = membro;
       this.texto = texto;
    }
    
    public Noticia(int id, String manchete, String texto){
        this.id = id;
        this.manchete = manchete;
        this.texto = texto;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    public String getManchete() {
        return manchete;
    }

    public void setManchete(String manchete) {
        this.manchete = manchete;
    }
    
    public Evento getEvento() {
        return this.evento;
    }
    
    public void setEvento(Evento evento) {
        this.evento = evento;
    }
    public Membro getMembro() {
        return this.membro;
    }
    
    public void setMembro(Membro membro) {
        this.membro = membro;
    }
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }

    public static List<Noticia> listarTodos(){
        List objects = HibernateUtil.getTuplasDaTabela("noticias");
        Returner<Noticia> returner = new Returner();
        return returner.getListaEspecifica(objects);
    }

}


