package Classes;
// Generated 28/05/2016 22:16:45 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ArquivoTurmaId generated by hbm2java
 */
public class ArquivoTurmaId  implements java.io.Serializable {
     private int idArquivo;
     private String codDisc;
     private Date dataInicio;

    public ArquivoTurmaId() {
    }

    public ArquivoTurmaId(int idArquivo, String codDisc, Date dataInicio) {
       this.idArquivo = idArquivo;
       this.codDisc = codDisc;
       this.dataInicio = dataInicio;
    }
   
    public int getIdArquivo() {
        return this.idArquivo;
    }
    
    public void setIdArquivo(int idArquivo) {
        this.idArquivo = idArquivo;
    }
    public String getCodDisc() {
        return this.codDisc;
    }
    
    public void setCodDisc(String codDisc) {
        this.codDisc = codDisc;
    }
    public Date getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArquivoTurmaId) ) return false;
		 ArquivoTurmaId castOther = ( ArquivoTurmaId ) other; 
         
		 return (this.getIdArquivo()==castOther.getIdArquivo())
 && ( (this.getCodDisc()==castOther.getCodDisc()) || ( this.getCodDisc()!=null && castOther.getCodDisc()!=null && this.getCodDisc().equals(castOther.getCodDisc()) ) )
 && ( (this.getDataInicio()==castOther.getDataInicio()) || ( this.getDataInicio()!=null && castOther.getDataInicio()!=null && this.getDataInicio().equals(castOther.getDataInicio()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdArquivo();
         result = 37 * result + ( getCodDisc() == null ? 0 : this.getCodDisc().hashCode() );
         result = 37 * result + ( getDataInicio() == null ? 0 : this.getDataInicio().hashCode() );
         return result;
   }   


}


