package Classes;
// Generated 28/05/2016 22:16:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Disciplina generated by hbm2java
 */
public class Disciplina  implements java.io.Serializable {


     private String codigo;
     private Seminario seminario;
     private String nome;
     private Set turmas = new HashSet(0);

    public Disciplina() {
    }

	
    public Disciplina(String codigo, Seminario seminario, String nome) {
        this.codigo = codigo;
        this.seminario = seminario;
        this.nome = nome;
    }
    public Disciplina(String codigo, Seminario seminario, String nome, Set turmas) {
       this.codigo = codigo;
       this.seminario = seminario;
       this.nome = nome;
       this.turmas = turmas;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Seminario getSeminario() {
        return this.seminario;
    }
    
    public void setSeminario(Seminario seminario) {
        this.seminario = seminario;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getTurmas() {
        return this.turmas;
    }
    
    public void setTurmas(Set turmas) {
        this.turmas = turmas;
    }




}


