package Classes;
// Generated 28/05/2016 22:16:45 by Hibernate Tools 4.3.1


import java.sql.Time;
import java.util.Date;

/**
 * EventoId generated by hbm2java
 */
public class EventoId  implements java.io.Serializable {
     private String tema;
     private Date dia;
     private Time hora;

    public EventoId() {
    }

    public EventoId(String tema, Date diaHora) {
       this.tema = tema;
       this.dia = diaHora;
    }
   
    public String getTema() {
        return this.tema;
    }
    
    public void setTema(String tema) {
        this.tema = tema;
    }
    public Date getDia() {
        return this.dia;
    }
    
    public void setDia(Date dia) {
        this.dia = dia;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EventoId) ) return false;
		 EventoId castOther = ( EventoId ) other; 
         
		 return ( (this.getTema()==castOther.getTema()) || ( this.getTema()!=null && castOther.getTema()!=null && this.getTema().equals(castOther.getTema()) ) )
 && ( (this.getDia()==castOther.getDia()) || ( this.getDia()!=null && castOther.getDia()!=null && this.getDia().equals(castOther.getDia()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTema() == null ? 0 : this.getTema().hashCode() );
         result = 37 * result + ( getDia() == null ? 0 : this.getDia().hashCode() );
         return result;
   }   


}


