package Classes;
// Generated 28/05/2016 22:16:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Matricula generated by hbm2java
 */
public class Matricula  implements java.io.Serializable {


     private MatriculaId id;
     private Membro membro;
     private Turma turma;
     private Float notaFinal;
     private Set assiduidades = new HashSet(0);

    public Matricula() {
    }

	
    public Matricula(MatriculaId id, Membro membro, Turma turma) {
        this.id = id;
        this.membro = membro;
        this.turma = turma;
    }
    public Matricula(MatriculaId id, Membro membro, Turma turma, Float notaFinal, Set assiduidades) {
       this.id = id;
       this.membro = membro;
       this.turma = turma;
       this.notaFinal = notaFinal;
       this.assiduidades = assiduidades;
    }
   
    public MatriculaId getId() {
        return this.id;
    }
    
    public void setId(MatriculaId id) {
        this.id = id;
    }
    public Membro getMembro() {
        return this.membro;
    }
    
    public void setMembro(Membro membro) {
        this.membro = membro;
    }
    public Turma getTurma() {
        return this.turma;
    }
    
    public void setTurma(Turma turma) {
        this.turma = turma;
    }
    public Float getNotaFinal() {
        return this.notaFinal;
    }
    
    public void setNotaFinal(Float notaFinal) {
        this.notaFinal = notaFinal;
    }
    public Set getAssiduidades() {
        return this.assiduidades;
    }
    
    public void setAssiduidades(Set assiduidades) {
        this.assiduidades = assiduidades;
    }




}


