package Classes;
// Generated 28/05/2016 22:16:45 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Membro generated by hbm2java
 */
public class Membro  implements java.io.Serializable {
     private int id;
     private Membro membro;
     private Pessoa pessoa;
     private String cpf;
     private Date dataNasc;
     private Date batismoApres;
     private boolean lider;
     private boolean professor;
     private String usuario;
     private String senha;
     private Set ministerios_part = new HashSet(0);
     private Set matriculas = new HashSet(0);
     private Set ministerios_lider = new HashSet(0);
     private Set turmas = new HashSet(0);
     private Set membros = new HashSet(0);
     private Set noticias = new HashSet(0);
     private Set seminarios = new HashSet(0);

    public Membro() {
    }

	
    public Membro(Membro membro, Pessoa pessoa, String cpf, Date dataNasc, boolean lider, boolean professor, String usuario, String senha) {
        this.membro = membro;
        this.pessoa = pessoa;
        this.cpf = cpf;
        this.dataNasc = dataNasc;
        this.lider = lider;
        this.professor = professor;
        this.usuario = usuario;
        this.senha = senha;
    }
    public Membro(Membro membro, Pessoa pessoa, String cpf, Date dataNasc, Date batismoApres, boolean lider, boolean professor, String usuario, String senha, Set ministerios, Set seminarios, Set matriculas, Set ministerios_1, Set turmas, Set membros, Set noticias) {
       this.membro = membro;
       this.pessoa = pessoa;
       this.cpf = cpf;
       this.dataNasc = dataNasc;
       this.batismoApres = batismoApres;
       this.lider = lider;
       this.professor = professor;
       this.usuario = usuario;
       this.senha = senha;
       this.ministerios_part = ministerios;
       this.seminarios = seminarios;
       this.matriculas = matriculas;
       this.ministerios_lider = ministerios_1;
       this.turmas = turmas;
       this.membros = membros;
       this.noticias = noticias;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Membro getMembro() {
        return this.membro;
    }
    
    public void setMembro(Membro membro) {
        this.membro = membro;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public Date getDataNasc() {
        return this.dataNasc;
    }
    
    public void setDataNasc(Date dataNasc) {
        this.dataNasc = dataNasc;
    }
    public Date getBatismoApres() {
        return this.batismoApres;
    }
    
    public void setBatismoApres(Date batismoApres) {
        this.batismoApres = batismoApres;
    }
    public boolean isLider() {
        return this.lider;
    }
    
    public void setLider(boolean lider) {
        this.lider = lider;
    }
    public boolean isProfessor() {
        return this.professor;
    }
    
    public void setProfessor(boolean professor) {
        this.professor = professor;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Set getMinisterios_part() {
        return this.ministerios_part;
    }
    
    public void setMinisterios_part(Set ministerios_part) {
        this.ministerios_part = ministerios_part;
    }
    
    public Set getSeminarios() {
        return this.seminarios;
    }
    
    public void setSeminarios(Set seminarios) {
        this.seminarios = seminarios;
    }
    
    public Set getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set matriculas) {
        this.matriculas = matriculas;
    }
    public Set getMinisterios_lider() {
        return this.ministerios_lider;
    }
    
    public void setMinisterios_lider(Set ministerios_lider) {
        this.ministerios_lider = ministerios_lider;
    }
    public Set getTurmas() {
        return this.turmas;
    }
    
    public void setTurmas(Set turmas) {
        this.turmas = turmas;
    }
    public Set getMembros() {
        return this.membros;
    }
    
    public void setMembros(Set membros) {
        this.membros = membros;
    }
    public Set getNoticias() {
        return this.noticias;
    }
    
    public void setNoticias(Set noticias) {
        this.noticias = noticias;
    }
    
    //



}


