package Classes;
// Generated 28/05/2016 22:16:45 by Hibernate Tools 4.3.1



/**
 * MidiaNoticiaId generated by hbm2java
 */
public class MidiaNoticiaId  implements java.io.Serializable {


     private int idMidia;
     private String manchete;

    public MidiaNoticiaId() {
    }

    public MidiaNoticiaId(int idMidia, String manchete) {
       this.idMidia = idMidia;
       this.manchete = manchete;
    }
   
    public int getIdMidia() {
        return this.idMidia;
    }
    
    public void setIdMidia(int idMidia) {
        this.idMidia = idMidia;
    }
    public String getManchete() {
        return this.manchete;
    }
    
    public void setManchete(String manchete) {
        this.manchete = manchete;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MidiaNoticiaId) ) return false;
		 MidiaNoticiaId castOther = ( MidiaNoticiaId ) other; 
         
		 return (this.getIdMidia()==castOther.getIdMidia())
 && ( (this.getManchete()==castOther.getManchete()) || ( this.getManchete()!=null && castOther.getManchete()!=null && this.getManchete().equals(castOther.getManchete()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdMidia();
         result = 37 * result + ( getManchete() == null ? 0 : this.getManchete().hashCode() );
         return result;
   }   


}


