package Classes;
// Generated 28/05/2016 22:16:45 by Hibernate Tools 4.3.1



/**
 * MidiaNoticia generated by hbm2java
 */
public class MidiaNoticia  implements java.io.Serializable {


     private MidiaNoticiaId id;
     private Noticia noticia;
     private String midia;

    public MidiaNoticia() {
    }

    public MidiaNoticia(MidiaNoticiaId id, Noticia noticia, String midia) {
       this.id = id;
       this.noticia = noticia;
       this.midia = midia;
    }
   
    public MidiaNoticiaId getId() {
        return this.id;
    }
    
    public void setId(MidiaNoticiaId id) {
        this.id = id;
    }
    public Noticia getNoticia() {
        return this.noticia;
    }
    
    public void setNoticia(Noticia noticia) {
        this.noticia = noticia;
    }
    public String getMidia() {
        return this.midia;
    }
    
    public void setMidia(String midia) {
        this.midia = midia;
    }




}


