package Classes;
// Generated 28/05/2016 22:16:45 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ministerio generated by hbm2java
 */
public class Ministerio  implements java.io.Serializable {


     private String nome;
     private Membro membro;
     private String descricao;
     private Date hora;
     private String diaSemana;
     private Set membros = new HashSet(0);

    public Ministerio() {
    }

	
    public Ministerio(String nome, Membro membro, Date hora, String diaSemana) {
        this.nome = nome;
        this.membro = membro;
        this.hora = hora;
        this.diaSemana = diaSemana;
    }
    public Ministerio(String nome, Membro membro, String descricao, Date hora, String diaSemana, Set membros) {
       this.nome = nome;
       this.membro = membro;
       this.descricao = descricao;
       this.hora = hora;
       this.diaSemana = diaSemana;
       this.membros = membros;
    }
   
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Membro getMembro() {
        return this.membro;
    }
    
    public void setMembro(Membro membro) {
        this.membro = membro;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public String getDiaSemana() {
        return this.diaSemana;
    }
    
    public void setDiaSemana(String diaSemana) {
        this.diaSemana = diaSemana;
    }
    public Set getMembros() {
        return this.membros;
    }
    
    public void setMembros(Set membros) {
        this.membros = membros;
    }

    /////////////////////////////////////////////////////////////////////
    
    /**
     * Em ministério, considera-se que o membro já esteja cadastrado no sistema
     * @param membro 
     */
    public void adicionarMembro(Membro membro){
        
    }


}


