package Classes;
// Generated 28/05/2016 22:16:45 by Hibernate Tools 4.3.1



/**
 * Ministra generated by hbm2java
 */
public class Ministra  implements java.io.Serializable {


     private MinistraId id;
     private Evento evento;
     private Mensagem mensagem;
     private Pessoa pessoa;

    public Ministra() {
    }

    public Ministra(MinistraId id, Evento evento, Mensagem mensagem, Pessoa pessoa) {
       this.id = id;
       this.evento = evento;
       this.mensagem = mensagem;
       this.pessoa = pessoa;
    }
   
    public MinistraId getId() {
        return this.id;
    }
    
    public void setId(MinistraId id) {
        this.id = id;
    }
    public Evento getEvento() {
        return this.evento;
    }
    
    public void setEvento(Evento evento) {
        this.evento = evento;
    }
    public Mensagem getMensagem() {
        return this.mensagem;
    }
    
    public void setMensagem(Mensagem mensagem) {
        this.mensagem = mensagem;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }




}


