package Classes;
// Generated 28/05/2016 22:16:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PeriodoLetivo generated by hbm2java
 */
public class PeriodoLetivo  implements java.io.Serializable {
     private int anoLetivo;
     private Seminario seminario;
     private Set turmas = new HashSet(0);

    public PeriodoLetivo() {
    }

	
    public PeriodoLetivo(int anoLetivo, Seminario seminario) {
        this.anoLetivo = anoLetivo;
        this.seminario = seminario;
    }
    public PeriodoLetivo(int anoLetivo, Seminario seminario, Set turmas) {
       this.anoLetivo = anoLetivo;
       this.seminario = seminario;
       this.turmas = turmas;
    }
   
    public int getAnoLetivo() {
        return this.anoLetivo;
    }
    
    public void setAnoLetivo(int anoLetivo) {
        this.anoLetivo = anoLetivo;
    }
    public Seminario getSeminario() {
        return this.seminario;
    }
    
    public void setSeminario(Seminario seminario) {
        this.seminario = seminario;
    }
    public Set getTurmas() {
        return this.turmas;
    }
    
    public void setTurmas(Set turmas) {
        this.turmas = turmas;
    }




}


