package Classes;
// Generated 28/05/2016 22:16:45 by Hibernate Tools 4.3.1


import Util.MinistraDao;
import java.util.HashSet;
import java.util.Set;

/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {
     private Integer id;
     private String nome;
     private String sobrenome;
     private String telefone;
     private String endRua;
     private Integer endNumero;
     private String endComp;
     private String endBairro;
     private String endCidade;
     private String endEstado;
     private String email;
     private Character estadoCivil;
     
     private Set ministras = new HashSet(0);
     private Visitante visitante;
     private Membro membro;
     
     private MinistraDao ministraDao;

    public Pessoa() {
        this.ministraDao = new MinistraDao();
    }

	
    public Pessoa(String nome, String sobrenome) {
        this.nome = nome;
        this.sobrenome = sobrenome;
        this.ministraDao = new MinistraDao();
    }
    public Pessoa(String nome, String sobrenome, String telefone, String endRua, Integer endNumero, String endComp, String endBairro, String endCidade, String endEstado, String email, Character estadoCivil, Set ministras, Visitante visitante, Membro membro) {
       this.nome = nome;
       this.sobrenome = sobrenome;
       this.telefone = telefone;
       this.endRua = endRua;
       this.endNumero = endNumero;
       this.endComp = endComp;
       this.endBairro = endBairro;
       this.endCidade = endCidade;
       this.endEstado = endEstado;
       this.email = email;
       this.estadoCivil = estadoCivil;
       this.ministras = ministras;
       this.visitante = visitante;
       this.membro = membro;
       this.ministraDao = new MinistraDao();
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSobrenome() {
        return this.sobrenome;
    }
    
    public void setSobrenome(String sobrenome) {
        this.sobrenome = sobrenome;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getEndRua() {
        return this.endRua;
    }
    
    public void setEndRua(String endRua) {
        this.endRua = endRua;
    }
    public Integer getEndNumero() {
        return this.endNumero;
    }
    
    public void setEndNumero(Integer endNumero) {
        this.endNumero = endNumero;
    }
    public String getEndComp() {
        return this.endComp;
    }
    
    public void setEndComp(String endComp) {
        this.endComp = endComp;
    }
    public String getEndBairro() {
        return this.endBairro;
    }
    
    public void setEndBairro(String endBairro) {
        this.endBairro = endBairro;
    }
    public String getEndCidade() {
        return this.endCidade;
    }
    
    public void setEndCidade(String endCidade) {
        this.endCidade = endCidade;
    }
    public String getEndEstado() {
        return this.endEstado;
    }
    
    public void setEndEstado(String endEstado) {
        this.endEstado = endEstado;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Character getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(Character estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
   
    public Set getMinistras() {
        return this.ministras;
    }
    
    public void setMinistras(Set ministras) {
        this.ministras = ministras;
    }
    public Visitante getVisitante() {
        return this.visitante;
    }
    
    public void setVisitante(Visitante visitante) {
        this.visitante = visitante;
    }
    public Membro getMembro() {
        return this.membro;
    }
    
    public void setMembro(Membro membro) {
        this.membro = membro;
    }

    public void cadastrarMinistracao(Evento evento, Mensagem mensagem){
        cadastrarMinistracao(new Ministra(new MinistraId(evento.getId().getTema(),evento.getId().getDiaHora(),mensagem.getTitulo()),evento,mensagem,this));
    }
    
    public void cadastrarMinistracao(Ministra ministra){
        ministraDao.gravar(ministra);
    }


}


