package Classes;
// Generated 28/05/2016 22:16:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Seminario generated by hbm2java
 */
public class Seminario  implements java.io.Serializable {


     private String nome;
     private Pessoa pessoa;
     private Set disciplinas = new HashSet(0);
     private Set periodoLetivos = new HashSet(0);

    public Seminario() {
    }

	
    public Seminario(String nome, Pessoa pessoa) {
        this.nome = nome;
        this.pessoa = pessoa;
    }
    public Seminario(String nome, Pessoa pessoa, Set disciplinas, Set periodoLetivos) {
       this.nome = nome;
       this.pessoa = pessoa;
       this.disciplinas = disciplinas;
       this.periodoLetivos = periodoLetivos;
    }
   
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Set getDisciplinas() {
        return this.disciplinas;
    }
    
    public void setDisciplinas(Set disciplinas) {
        this.disciplinas = disciplinas;
    }
    public Set getPeriodoLetivos() {
        return this.periodoLetivos;
    }
    
    public void setPeriodoLetivos(Set periodoLetivos) {
        this.periodoLetivos = periodoLetivos;
    }




}


