package Classes;
// Generated 28/05/2016 22:16:45 by Hibernate Tools 4.3.1


import Util.DisciplinaDao;
import Util.PeriodoLetivoDao;
import java.util.HashSet;
import java.util.Set;

/**
 * Seminario generated by hbm2java
 */
public class Seminario  implements java.io.Serializable {
     private String nome;
     private Membro membro;
     private Set disciplinas = new HashSet(0);
     private Set periodoLetivos = new HashSet(0);
     private PeriodoLetivoDao periodoLetivoDao;
     private DisciplinaDao disciplinaDao;

    public Seminario() {
        this.periodoLetivoDao = new PeriodoLetivoDao();
        this.disciplinaDao = new DisciplinaDao();
    }

	
    public Seminario(String nome, Membro membro) {
        this.nome = nome;
        this.membro = membro;
        this.periodoLetivoDao = new PeriodoLetivoDao();
        this.disciplinaDao = new DisciplinaDao();
    }
    
    public Seminario(String nome, Membro membro, Set disciplinas, Set periodoLetivos) {
       this.nome = nome;
       this.membro = membro;
       this.disciplinas = disciplinas;
       this.periodoLetivos = periodoLetivos;
       this.periodoLetivoDao = new PeriodoLetivoDao();
       this.disciplinaDao = new DisciplinaDao();
    }
   
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Membro getMembro() {
        return this.membro;
    }
    
    public void setMembro(Membro membro) {
        this.membro = membro;
    }
    public Set getDisciplinas() {
        return this.disciplinas;
    }
    
    public void setDisciplinas(Set disciplinas) {
        this.disciplinas = disciplinas;
    }
    public Set getPeriodoLetivos() {
        return this.periodoLetivos;
    }
    
    public void setPeriodoLetivos(Set periodoLetivos) {
        this.periodoLetivos = periodoLetivos;
    }

    /**
     * Adiciona mais um período letivo - poderia ser feito automaticamente
     * Usa a Session do Hibernate para realizar a transação em salvar o novo período
     * @param ano: ano do período letivo
     */
    public void cadastrarPeriodoLetivo(int ano){
        PeriodoLetivo pLetivo = new PeriodoLetivo(ano, this);
        periodoLetivoDao.gravar(pLetivo);
    }

    public void cadastrarDisciplina(String codigo, String nome){
        cadastrarDisciplina(new Disciplina(codigo,this,nome));
    }
    
    public void cadastrarDisciplina(Disciplina disciplina){
        disciplinaDao.gravar(disciplina);
    }
}
