package Classes;
// Generated 28/05/2016 22:16:45 by Hibernate Tools 4.3.1


import Util.MatriculaDao;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Turma generated by hbm2java
 */
public class Turma  implements java.io.Serializable {
     private TurmaId id;
     private Disciplina disciplina;
     private Membro professor;
     private PeriodoLetivo periodoLetivo;
     private Date dataFim;
     private Set matriculas = new HashSet(0);
     private MatriculaDao matriculaDao;
    
    public Turma() {
        this.matriculaDao = new MatriculaDao();
    }

	
    public Turma(TurmaId id, Disciplina disciplina, Membro membro, PeriodoLetivo periodoLetivo, Date dataFim) {
        this.id = id;
        this.disciplina = disciplina;
        this.professor = membro;
        this.periodoLetivo = periodoLetivo;
        this.dataFim = dataFim;
        this.matriculaDao = new MatriculaDao();
    }
    public Turma(TurmaId id, Disciplina disciplina, Membro membro, PeriodoLetivo periodoLetivo, Date dataFim, Set matriculas) {
       this.id = id;
       this.disciplina = disciplina;
       this.professor = membro;
       this.periodoLetivo = periodoLetivo;
       this.dataFim = dataFim;
       this.matriculas = matriculas;
       this.matriculaDao = new MatriculaDao();
    }
   
    public TurmaId getId() {
        return this.id;
    }
    
    public void setId(TurmaId id) {
        this.id = id;
    }
    public Disciplina getDisciplina() {
        return this.disciplina;
    }
    
    public void setDisciplina(Disciplina disciplina) {
        this.disciplina = disciplina;
    }
    public Membro getProfessor() {
        return this.professor;
    }
    
    public void setProfessor(Membro professor) {
        this.professor = professor;
    }
    public PeriodoLetivo getPeriodoLetivo() {
        return this.periodoLetivo;
    }
    
    public void setPeriodoLetivo(PeriodoLetivo periodoLetivo) {
        this.periodoLetivo = periodoLetivo;
    }
    public Date getDataFim() {
        return this.dataFim;
    }
    
    public void setDataFim(Date dataFim) {
        this.dataFim = dataFim;
    }
   
    public Set getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set matriculas) {
        this.matriculas = matriculas;
    }

    /////////////////////////////////////////////////////////////
    
    public void cadastrarMatricula(Membro aluno){
        cadastrarMatricula(new Matricula(new MatriculaId(aluno.getId(),disciplina.getCodigo(),id.getDataInicio()),aluno,this));
    }
    
    public void cadastrarMatricula(Matricula matricula){
        matriculaDao.gravar(matricula);
    }
    
    public List<Membro> getListaDeAlunos(){
        List<Membro> alunos = new ArrayList<>();
        
        return alunos;
    }
            


}


